manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: 280Zo
      url-base: https://github.com/280Zo

    - name: moverisJustin
      url-base: https://github.com/moverisJustin

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-dongle-screen
      remote: moverisJustin
      revision: main

  self:
    path: config
